pipeline {
    agent none
    stages {
        stage('Docker up') { 
            agent any
            steps {
                echo 'Docker up...'
                sh 'docker build -f Dockerfile -t maven:latest .'
                sh 'docker run -d -v /root/.m2:/root/m2 --name=maven maven:latest'
                sh 'docker cp /root/.m2 maven:/root/.m2' 
            }
        }

        stage('Build') { 
            agent {
                docker 'maven:latest'
            }
            steps {
                echo 'Build...'
                sh 'mvn install -Dhttps.proxyHost=${HOST} -Dhttps.proxyPort=${PORT}'
                sh 'mvn -B -DskipTests clean package' 
            }
        }

        stage('Test') {
            agent {
                docker 'maven:latest'
            }
            steps {
                sh 'mvn test'
            }
        }
    }
}